import type { Metadata } from "next";
import { Changa, Coustard } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

export const changaSans = Changa({
  variable: "--font-changa",
  subsets: ["latin"],
  weight: ["400"],
});

const courstardSans = Coustard({
  variable: "--font-courstard-sans",
  subsets: ["latin"],
  weight: ["400", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-background text-foreground ${changaSans.className} ${courstardSans.className} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          {/* <ThemeToggle/> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
