type UserInfo = {
  name: string;
  lastName: string;
  profilePhotoUrl: string;
  urls: string[];
};

export type Project = {
  url: string;
  name: string;
};

export type Background = {
  id: string;
  year: number;
  title: string;
  description: string;
  location?: string;
  durationInMonths?: number;
  isCurrent?: boolean;
  month?: number;
  projects?: Project[];
  isInactive?: boolean;
};

type UserBackground = Background[];

export const listOfYears = [
  1997, 2016, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025,
];

export const userData: UserInfo = {
  name: "Alek",
  lastName: "Lima",
  profilePhotoUrl: "https://github.com/AlekLima.png",
  urls: [
    "https://github.com/AlekLima",
    "https://www.linkedin.com/in/alekteles/",
    // "https://www.turma.dev",
  ],
};

export const contentData: UserBackground = [
  {
    id: "bg-1997-09",
    year: 2000,
    month: 7,
    title: "Birth🚩",
    description: "Brazilian, Fortaleza resident",
    location: "Fortaleza/CE",
  },
  {
    id: "bg-2013-02",
    year: 2022,
    month: 9,
    title: "First Encounter With Coding",
    description: "First Projects: Disney Clone, Fridge,  \n -  HTML e CSS",
    projects: [
      {
        url: "https://fireblogs-bdcc3.web.app",
        name: "Fire Blogs",
      },
      
      {
        url: "https://disney-clne.vercel.app",
        name: "Disney clone",
      },

      {
        url: "https://fridge-html-xi.vercel.app",
        name: "Projeto Fridge",
      },
      
    ],

  },
  {
    id: "bg-2016-03",
    year: 2023,
    month: 2,
    title: "Ingressed in University Estácio de Sá",
    description: "Bachelor´s degree in Computer Science",
    location: "Fortaleza/CE",
  },
  
  {
    id: "bg-2022-12b",
    year: 2024,
    month: 2,
    title: "Ingressed in Ignite Specialization Course 🚀",
    description: "Start of specialization program in Node/Typescript by @Rocktseat",
    projects: [
      {
        url: "https://github.com/AlekLima/Design-de-software-e-DDD",
        name: "Software Design and DDD",
      },
      {
        url: "https://github.com/AlekLima/Gympass-Solid",
        name: "Gympass Clone using Principles Solid",
      },
      {
        url: "https://github.com/AlekLima/FindFriendAPI",
        name: "FindFriendAPI, final coding challenge",
      },
    ],
  },
  {
    id: "bg-2023-03",
    year: 2023,
    month: 3,
    title: "First College Certificates",
    description: "First of Many Achievements",
    projects: [
      {
        url: "https://bucket-app-microcertificados.s3.amazonaws.com/ESTACIO/610/9188401/a163747fb9ab0df6c755a3557220d9a-724c-43b8-bfdd-4e7bec9dcf6a",
        name: "Design of Efficient, Stable, and Scalable Algorithms",
      },
      {
        url: "https://drive.google.com/file/d/1xiOtPuh0a_4h6AWNGCV4h0PjTyE8niS4/view?usp=sharing",
        name: "Management, Organization, and Information Retrieval",
      },
      {
        url: "https://drive.google.com/file/d/1xiOtPuh0a_4h6AWNGCV4h0PjTyE8niS4/view?usp=sharing",
        name: "Information Systems Programing",
      },
      {
        url: "https://drive.google.com/file/d/1xiOtPuh0a_4h6AWNGCV4h0PjTyE8niS4/view?usp=sharing",
        name: "Internet Programing",
      },
      {
       url: "https://drive.google.com/file/d/1sUtlb_UEGq6311YbM4tpDZmUnQmYVwop/view?usp=sharing",
        name: "Comunity Engagement and Transformative Practice",
      }
    ],
  },
  {
    id: "bg-2023-06",
    year: 2023,
    month: 6,
    title: "First Freelance",
    description: "Website for selling air conditioning solutions and accessories",
    projects: [
      {
        url: "https://github.com/AlekTeles/mwv",
        name: "mwrefrigerações",
      },
    ],
  },
  {
    id: "bg-2024-12",
    year: 2024,
    month: 12,
    title: "Specialized Certificate in React and Next.js🏅",
    description: "The end of a long road in Node and Typescript in @Rocktseat",
    projects: [
      {
        url: "https://app.rocketseat.com.br/certificates/cce107e9-abdf-49df-8e9d-2379d039efe7",
        name: "Node Fundamentals",
      },
      {
        url: "https://app.rocketseat.com.br/certificates/8eaecca1-f2b9-4161-9660-17edb9b14b1e",
        name: "DDD in Node",
      },
      {
        url: "https://app.rocketseat.com.br/certificates/ab930663-c6eb-4057-8c56-4c42f738afc1",
        name: "NestJS",
      },
      {
        url: "https://app.rocketseat.com.br/certificates/7c9f4311-ad15-4c5f-8028-d22b65b1705d",
        name: "Ignite - Certificate in Node",
      },
    ],
  },
  
  {
    id: "bg-2025-01",
    year: 2025,
    month: 1,
    title: "Started studies in LLM and Open Source 🌐",
    description:
      "Started to study RAG, CI pipelines for LLM outputs,Test generation & mutation testing",
  },

   {
    id: "bg-2021-04",
    year: 2025,
    month: 11,
    title: "Dev LLM expert at Revelo 📲",
    description:
      "Evaluation and correction of code generated by an Artificial Agent",
    
  },
];